name: Terraform CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - '*'

permissions:
    contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ vars.TFLINT_DEFAULT_VERSION && format('v{0}', vars.TFLINT_DEFAULT_VERSION) || 'latest' }}

      - name: Run TFLint
        run: tflint -f compact

  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_DEFAULT_VERSION && vars.TERRAFORM_DEFAULT_VERSION || 'latest' }}

      - name: Check formatting
        run: |
          terraform fmt -recursive -check

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_DEFAULT_VERSION && vars.TERRAFORM_DEFAULT_VERSION || 'latest' }}

      - name: Init module
        run: |
          terraform init -backend=false

      - name: Validate module
        run: |
          terraform validate

  docs-check:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4
      - uses: terraform-docs/gh-actions@v1.2.0
        with:
          config-file: .terraform-docs.yml
          fail-on-diff: ${{ github.event_name != 'pull_request' }}
          git-push: ${{ github.event_name == 'pull_request' }}
