name: Terraform CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - main

    tags:
      - '*'

permissions: write-all

jobs:
  terraform:
    uses: Schumann-IT/terraform-gh-workflows/.github/workflows/terraform.yaml@main
    secrets: inherit
  changelog:
    uses: Schumann-IT/terraform-gh-workflows/.github/workflows/changelog.yaml@main
    secrets: inherit
